### ISSUE TITLE
ASC-DB GLAARG counts no FINISH.

### ISSUE THREAD

**Issue by Crashsolver** [tkocou/ASC#1]
Installed version 1 for the last 10 days I try to import GLAARG stats. In less than a minute I see updating database then it stops and I never receive the Finish. The GLAARG date above never changes. I have run it for 1 hour, 3 hours, and 6 hours with no change. The program does not freeze.

Windows 10 Pro.

ARRL import works fine.

I do know there has been tweaking going on with the GLAARG site, but do not know the source of the issue, program or site.

Dave N4NG

**Comment by tkocou** [comment]
The basic import function had a not so easy to spot logic problem. The new version 1.2 has the fix. Might be easier to delete the asc.db file and let ASC-DB rebuild the database.

**Comment by Crashsolver** [comment]
Many thanks, I found that while it did not say it was finished and the date never updated. The DB did update. Just did not indicate that it had. The ARRL side functioned fine. Dave N4NGSent from my iPhoneOn Nov 28, 2023, at 17:14, tkocou ***@***.***> wrote:﻿
The basic import function had a not so easy to spot logic problem. The new version 1.2 has the fix. Might be easier to delete the asc.db file and let ASC-DB rebuild the database.
